use_frameworks!

platform :ios, '10.0'

target 'SDKNetwork_Example' do
  pod 'SDKNetwork', :path => '../'

  target 'SDKNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
